Nikkei/atlas-tracking-js

src/utils.js
This PR allows setting device id in 3rd party context.
=> Allow setting device id in 3rd party context.

package-lock.json, package.json
**Merged pull requests:**
- Add track navigation [\#29](https://github.com/Nikkei/atlas-tracking-js/pull/29)
=> Update version to v2.13.1.

package-lock.json, package.json
Reverts Nikkei/atlas-tracking-js#32
=> Revert "Update version to v2.13.1."

.circleci/config.yml
Version up circle ci image for integration testing environment.
=> Fix integration test environment.

package-lock.json, package.json
- Add track navigation #29 
- Added auto click tracking #35
=> Version up to 2.14.0.

package-lock.json, package.json
- exclude input tag from click tracking #39
=> Modify version to 2.14.1.

package-lock.json, package.json
- Add ability window select #45
=> Update to 2.14.2.

src/index.js, src/utils.js
To remove redundant code, this PR modify targetWindow initialization.
targetWindow is initialized at index and pass it as constructor argument of utils.
=> Initialize targe window once.

package-lock.json, package.json
Just update version code of package.json.
=> Update to 2.15.0.

.github/workflows/release.yml
Add Ciecle CI job to release artifact to Github.
=> Add github release job.

.github/workflows/release.yml
=> Fix ci job.

.github/workflows/release.yml
fix typo on github action workflow file.
=> Fix typo on github job config.

package-lock.json, package.json
=> Update to 2.15.2.

package-lock.json, package.json
=> Modify version to 2.15.3.

package-lock.json, package.json
=> Patch update to 2.15.4.

package-lock.json, package.json
=> Patch update to 2.15.5.

package-lock.json, package.json
=> Update to 2.15.6.

.github/workflows/build-and-test.yml
This PR migrates CI from CircleCI to github action.
=> Add test and build github action workflow.

src/utils.js
エラーハンドリングされていない変数に対する修正となります。
お手数ですがご確認のほど、よろしくお願いいたします。
=> set null if value is illegal

package-lock.json, package.json
- #81 
- #82 
- #83 
- #84 
- #85 
- #86 
- #88
=> Release v2.16.0.

package-lock.json, package.json
=> Version up to 2.16.1.

.github/workflows/build-and-test.yml
This PR updates nodejs version on test environment to ver 16.
=> Update node version of test environment to v16.

.github/workflows/release.yml
This PR changes node version of release image to current stable node version.
=> Change release image to current stable node version(16).

package-lock.json, package.json
=> Version up to 2.16.2.

docs/CONFIGURATION-JP.md, docs/CONFIGURATION.md
This PR fixes the sample value to the value actually used.
=> Change content_status sample

package-lock.json, package.json
=> Release v2.16.5.

src/index.js
=> Fixed behavior of `logAllClicks` option

package.json
=> Update version to v2.16.6.

package-lock.json, package.json
=> Update version to v2.16.7.

package-lock.json, package.json
=> Update version to 2.16.8
