src/index.js
`href`が設定されていない場合(広告など、リンククリック時の動作がjsで制御されている場合)にエラーが起きていたため修正
=> Fix accessing null object when link does not exist

package-lock.json, package.json
This PR fixes following 2 vulnerabilities.
- https://nodesecurity.io/advisories/739
- https://nodesecurity.io/advisories/736
=> Update morgan and cached-path-relative to fix vulnerabilities.

src/utils.js
This PR changes SDK_VERSION to be set from `package.json` 's version.
Sorry, I forgot to update `SDK_VERSION` to `2.12.5` in previous PR.
=> Set SDK_VERSION to version in package.json file.

src/utils.js
This PR fixes the issue that `matches is not a function` on IE.
Current implementation already care about IE, but this does not work for `SVGElement`.
So, this PR changes to support all elements which supports `matches` or `msMatchesSelector `.
=> Fix "matches is not a function" error on IE

src/index.js, src/utils.js
This PR removes cookie setting in script. `Set-Cookie` should be used to set cookie.
And to mitigate the effect of ITP2.1, it also introduces the backup method of device id.
=> Stop setting cookie in script.

package.json, src/utils.js
- replaced UUIDv4 with RAND based method
- removed Cookie module and getC is now REGEX based
- added Fetch based fallback to transmit(), this is recommended by Mozilla
note that all these changes are not verified due to restricted access to the latest endpoint.
=> suggestion for cumulative improvement

src/index.js
Add `AtlasTracking.disableTracking` method. When this called, all of tracking handlers and options are deleted. 
After that, user must call `AtlasTracking.initPage` to initialize tracking operations.
=> Add disable tracking

.circleci/config.yml, dist/c2p.js, docs/CONFIGURATION-JP.md, docs/CONFIGURATION.md, src/index.js, src/utils.js, test/integration/pages/src/default.js, test/integration/pages/src/track_media.js, test/integration/pages/src/track_read.js, test/integration/pages/src/track_viewability.js, test/test.html
This request will add the trackNavigation option.
```js
context.navigation: {
type: "reload"  // "navigate", "reload", "back_forward", "prerender"
redirectCount: 0,
domContentLoaded: 1023.12345,
first_paint: 1343.12345,
history_length: 3
}
```
This feature is partially overlapped with the Performance API.
trackNavigation extracts the items that are important for analysis,
and we are planning to modify the performance api as well.
=> Add track navigation

docs/CONFIGURATION-JP.md, docs/CONFIGURATION.md, src/index.js, src/utils.js
Today's ATJ measures click events on elements with data-attribute specified in targetAttribute option. With some sites, analysts want to measure clicks on all clickable elements without additional tagging work. This update contains the auto-track feature for click events on all clickable elements.
Original ATJ requires a `trackClick.targetAttribute` option for specifying the target element of trackClick. With this new auto-track feature, if  `trackClick.targetAttribute` is not specified, clicks on all clickable elements will be measured. So, the implementation work can be reduced.
=> Added auto click tracking

src/index.js
`input` tag is usually not a clickable element. This change could reduces unnecessary requests.
=> exclude input tag from click tracking

src/index.js
Current code tracks click events on every DOM. But every element does not have `element` attributes.
This PR introduce filtering condition before tracking click.
=> Check existence of element attribute before track click.

src/index.js
We changed the behavior of `clickTrack` for auto-track at ver 2.14.
However, there was a small glitch.
**Before 2.14**
If the clickTrack is enabled with `data-atlas-trackable` attribute, `ingest.context.action.name` will contain a value of the attribute.
**Since 2.14**
If the clickTrack is enabled without `data-atlas-trackable` attribute, all clicks on clickable element is tracked automatically & `ingest.context.action.name` will be removed (set `undefined` internally)
Even if the clickTrack is enabled with `data-atlas-trackable` attribute, `ingest.context.action.name` will be removed (set `undefined` internally)
**This PR**
If the clickTrack is enabled with `data-atlas-trackable` attribute, `ingest.context.action.name` will contain a value of the attribute. (same with pre-2.14)
=> Fix `name` attr which is permanently `undefined` since 2.14

src/utils.js
If the case of `(this.contentWindow === this)` is `false`, The previous code fail to evaluate `new AbortController()` because there is no `this.AbortController`.
For example, this issue would be happen if the user introduce `AbortController` as a polyfill to `this.contentWindow` but it's not loaed to `this`.
This original code path was introduced in https://github.com/Nikkei/atlas-tracking-js/commit/4141ebe740c9796027e73f818c3433a4271299a9. So this bug is exist from that time.
=> Call `new AbortController()` on the checked object properly.

src/utils.js
A function for reading Cookie in `util.js` has a bug; it truncates a value after string `S` because of wrong RegEx.
This bug is a potential cause of the shorter Atlas ID.
=> Fixed a function for reading Cookie

src/utils.js
The new cookie read function `getC()` in utils does not return a correct value of Cookie.
This PR is to fix it.
=> Fix a bug in the new Cookie Read function

dist/c2p.js
A sample file of c2p.js uses `null` if value of each field is not available, but it keeps nested fields (object).
By setting `undefined`, nested fields such as `contect.campaign` and `context.search` can remove empty attributes.
=> Update c2p.js sample: set `undefined` if UTM params not exist

src/index.js
With ATJ 2.15.x, unexpected script error happened if `trackClick` option is not set.
A root cause is `delegateClickEvents()` does not evaluate that `trackClick` option exists or not.
So, this PR is to add  a condition to check `trackClick` option which is the  parent of `obj.trackClick.enable`.
=> Fix a condition for triggering Click Tracking

src/index.js
- We saw the SDK send all events for milestone (time) based read-through measurement immediately just after SDK is initialized.
- This is not expected and may cause data accuracy.
- Restructured the logic inside `trackRead()` method.
- Confirmed that the events are sent on intended timing on local test page.
=> Fix a logic for Read Through measurement

src/index.js
This doesn't raise an error when the build target is es5 since `class` will become prototype base object.
However, when the build is ES2015 onward this will raise an error.
This is kinda OK when users of this JavaScript are transpiling es5, but when it's not. (and likely-hood this happens will be high since IE11 is officially not supported anymore)
=> fix: When the build target is ES2015, this give us TypeError.

src/index.js, src/utils.js
- Append a timestamp to Atlas ID.
- The same ID is used for both Atlas ID and Root ID to reduce generating unique ID.
- Replaced `Math.random()` with `getSecureRandom()`.
- Stopped using LocalStorage & removed unused LocalStorage related methods.
=> Improve a logic for generating unique ID

README.md
Remove CircleCI status from Readme because we don't use it anymore.
=> Remove CircleCI status indicator.

src/utils.js
IE does not support `crypto.getRandomValues()` so the unique ID generation using `Math.random()` is still needed.
This PR is to add a condition like `if (self.crypto.getRandomValues) {}else{}`to split the process based on the browser supports `getRandomValues` or not.
=> Added a fallback for IE compatibility

Dockerfile
- Use the long term support (LTS) version of Node.js
- Use the latest Docker image with Alpine
- Specified `python3` instead of `python`
=> Update build environment

dist/c2p.js, docs/CONFIGURATION-JP.md, docs/CONFIGURATION.md, src/index.js, src/utils.js
- Last Click feature is a solution for mis-tracking issue of beacons while unload event (especialy on Safari).
- ATJ's conventional click tracking send a beacon on click event, but some browsers in some cases, script & beacon may be canceled.
- Another method with link decorator (like adding `?cid=` param) is not recommended from SEO perspective (canonnical URL problem)
- How this work
- the Last Click feature stores information about clicked element into Session Storage when the click event occurred. 
- on the next page, ATJ read nformation from Session Storage, then add it under `context.last_click`.
- removed `cookieName` option because  no one use this.
- optimized logic in click event handler
- bug fix for Download click
=> Add "Last Click" feature

src/index.js
In the release of 2.16.*, some code that generates the ingest object has been minimized by reducing redundant scripts.
At that moment, we deleted a line for defining `ingest.context.page_name` accidentaly, then it affects lack of page_title from the log.
So, I'd like to re-add that necessary code. (restoring)
=> Bug Fix: added page_title field which is removed unexpectedly

.gitignore, src/index.js
This PR is to fix a bug in click measurement feature.
ATJ must send a beacon in case of following:
- `click.enable` is `true` AND  `click.targetAttribute` is not specified ( `undefined` or `false` )
- `click.enable` is `true` AND `click.targetAttribute` is specified AND the clicked element has an attribute specified as `targetAttribute`
However, as of now, ATJ send a beacon when `click.enable` is `true` AND  `click.targetAttribute` is specified AND the clicked element has no attribute eg. `data-atlas-trackable`. This behavior is unexpected and was inserted in the last version-up.
So, we need to fix this bug:
* `targetAttribute` is set as `data-atlas-trackable`
| click.enable | click.targetAttribute | expected | actual |
|:----|:----|:----|:----|
| `true` | `data-atlas-trackable` | …
=> Bug Fix) Added a trigger condition on click measurement 

package.json
This PR removes `--no-sandbox` chrome option to stop occasional test failures.
=> Remove `--no-sandbox` chrome option to stop occasional test failures.

dist/c2p.js, src/index.js
- In some analysis cases, `ingest.context.action.name` is expected for better query performance and query compatibility.
- When ATJ is initialized with click auto-trak (enable=true but targetAttribute=undefined), `action.name` will be undefined.
- However there is a need to activate auto track with `action.name` field.
so, this PR is to add `logAllClicks` option and enable both auto track && `action.name` at the same time.
=> Fix trackClick's automation with targetAttribute option

src/index.js
With Single Page Application (SPA), `initPage()` is called when the view is changed (eg. `onHashChange` ).
However, internal variables `pageLoadedAt` and `prevActionOccurredAt` are not reset by `initPage()`.
This causes a larger `elapsed_since_page_load` value than expected, in some variables under `ingest` object.
This PR is to add a code for resetting both `pageLoadedAt` and `prevActionOccurredAt` when the 2nd `initPage()` and later.
=> `pageLoadedAt` must be reset by initPage()

src/index.js
ATJ 2.16.6 added ability to enable both click measurement 1. semi-auto tracking with `data-trackable` and 2. full-auto tracking with `logAllClicks` option at the same time.
However, `ingest.context.action.location` is enexpectedly `undefined` when the full-auto is enabled and the element has `data-trackable` attribute.
This is caused by a bug in `delegateClickEvents()`. If `pathTrackable` is not provided, the value of `pathDom` should be kept.
So, this PR is to fix this bug.
=> Keep `pathDom` when `pathTrackable` is not provided

docs/CONFIGURATION-JP.md, docs/CONFIGURATION.md
In the [System Table in CONFIGURATION.md](https://github.com/Nikkei/atlas-tracking-js/blob/master/docs/CONFIGURATION.md#system), the `Purpose` column for the `cookieDomain` property, which is no longer used, is marked as **`DEPRECATED`**.
However, `cookieMaxAge` and `cookieDomain` are not currently used either, but they are not marked as deprecated.
So in this PR, I have changed the documentation to be consistent with the current code.
=> Update configuration documents to be consistent with the code

docs/CONFIGURATION-JP.md, docs/METHODS-JP.md
This pull request addresses a couple of typos in the Japanese documentation where "スクロール" was mistakenly typed as "スクロース." The affected instances have been corrected to "スクロール"
=> Fix typos in Japanese documentation

docs/CONFIGURATION-JP.md, docs/CONFIGURATION.md
- ATJ supports `logAllClicks` option in Click Track, but it was not documented. This PR is to add the description of this option.
=> Add description for click auto track (lack of documentation)

src/index.js
just a small change;
- `for( ~ of ~)` syntax is not supported in ES5 so the build script source a stiny polyfill code
- In the source code, there are both `for()` and `for( ~ of ~)`, but no policy here (I guess). So I suggest to reduce `for( ~ of ~)` use for reducing the bundle size smaller as possibule.
=> Reduce for ~ of polyfill

src/utils.js
Some of media players support changing the playback rate option.
This PR is to make ATJ able to record the playback rate.
=> Add playbackRate to Media Tracking
